version: '3.7'
services:
  web:
    image: node:latest
    environment:
      - NODE_ENV=production
      - WS_URL=http://web:3000
      - HOST=0.0.0.0
      - PORT=80
      - DB_HOST=database
      - MONGO_INITDB_DATABASE=chat
      - MONGO_INITDB_ROOT_USERNAME=gooff
      - MONGO_INITDB_ROOT_PASSWORD=gooff
    volumes:
      - ./:/app/
    working_dir: "/app/"
    ports:
      - 3000:3000
      - 8000:8000
    command: sh -c "pm2 start server/index.js"
    restart: always

